
CREATE TABLE PROJECT(ID NUMERIC(10),NAME VARCHAR(200),DESCRIPTION VARCHAR(500),MAXBUDGETAMOUNT NUMBER(10),BIDDINGENDTIME DATE,CREATEDDATE DATE,UPDATEDDATE DATE);

CREATE SEQUENCE PROJECT_SEQ START WITH 1 INCREMENT BY 5;

